version: '2.1'
orbs:
  compass: atlassian-labs/compass@0.1.3
jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
workflows:
  main-workflow:
    jobs:
      - deploy:
          context:
            - compass-integration-sbangaru-testing-three
          post-steps:
            - compass/notify_deployment:
                environment_type: production